- hosts: localhost
  connections: local
  gather_facts: False
  tasks:
    - name: import VPC Variables
      inlcude_vars: vars/vpc_setup

    - name: create vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout