---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
        include_vars: vars/vpc-output_vars

    - name: Import vprofile setup Variable
        include_vars: vars/vprostacksetup